require 'rspec'
require 'rspec/expectations'
require 'watir-webdriver'

require 'rspec'
require 'rspec/expectations'
require 'watir-webdriver'
require 'Faker'
require 'selenium-webdriver'
require 'clipboard'
require 'yaml'
require 'nokogiri'
require 'open-uri'
require 'zip'
require 'rubyXL'

